name: fazr
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  android_alarm_manager_plus: ^5.0.0
  cached_network_image: ^3.4.1
  cloud_firestore: ^6.0.1
  cupertino_icons: ^1.0.8
  easy_date_timeline: ^2.0.9
  firebase_auth: ^6.1.0
  firebase_core: ^4.1.0
  firebase_storage: ^13.0.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_local_notifications: ^19.4.2
  flutter_native_splash: ^2.4.6
  flutter_svg: ^2.2.1
  http: ^1.5.0
  image_picker: ^1.2.0
  intl: ^0.20.2
  path: ^1.9.1
  permission_handler: ^12.0.1
  provider: ^6.1.5+1
  rrule: ^0.2.17
  shared_preferences: ^2.5.3
  table_calendar: ^3.2.0
  timezone: ^0.10.1

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/icons/

  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-Regular.ttf
        - asset: assets/fonts/Urbanist-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Urbanist-Bold.ttf
          weight: 700
        - asset: assets/fonts/Urbanist-Black.ttf
          weight: 900

flutter_native_splash:
  color: "#EDEFF4"
  image: assets/icons/splash.png
  android_12:
    image: assets/icons/splash.png
    icon_background_color: "#EDEFF4"

  android: true
  ios: true
  web: true
